title: Darren Mascioli
email: darren.mascioli@pitt.edu
description: >- # this means to ignore newlines until "baseurl:"
  Aspiring Embedded Systems Engineer and Computer Engineering student at the University of Pittsburgh
baseurl: ""
url: "dmascioli.github.io"
github_username: dmascioli
instagram_username: dmas97
linkedin_username: darrenmascioli

# Build settings
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

google_analytics: UA—179228084-1

collections:
  courses:
    output: true
    permalink: /courses/:path/

defaults:
  - scope:
      path: ""
      type: "courses"
    values:
      layout: "course"
