# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Darren Mascioli
email: darren.mascioli@pitt.edu
description: >- # this means to ignore newlines until "baseurl:"
    Aspiring Embedded Systems Engineer and Computer Engineering student at the University of Pittsburgh 
baseurl: "" # the subpath of your site, e.g. /blog
url: "dmascioli.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  dmascioli
instagram_username: dmas97
linkedin_username: darrenmascioli

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-analytics

jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-175358884-1          # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


collections:
  courses:
    output: true
    permalink: /courses/:path/
    order: 
      - cs441.md
      - cs445.md
     # - coe147.md
     # - coe449.md
     # - coe501.md
     # - coe1502.md
     # - coe1541.md
     # - coe1501.md
     # - coe1520.md
     # - cs1550.md
     # - cs1632.md
     # - coe1530.md
     # - cs1555.md
     # - cs1656.md
     # - ece202.md
     # - cs1621.md
     # - cs1699.md
     # - ece1150.md
     # - ece1896.md
